version: "3.9"

services:
  mariadb:
    image: "bitnami/mariadb:latest"
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_USER=bn_laravel
      - MARIADB_PASSWORD=secret
      - MARIADB_DATABASE=bitnami_laravel
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - laravel_network

  app:
    image: "bitnami/laravel:latest"
    container_name: laravel
    ports:
      - "8000:8000"
      - "5173:5173" # Puerto para Vite
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_laravel
      - DB_USERNAME=bn_laravel
      - DB_PASSWORD=secret
      - BITNAMI_APP_USER=1000 # UID de tu usuario local
      - BITNAMI_APP_GROUP=1000 # GID de tu usuario local
    volumes:
      - './my_laravel_app:/app'
    networks:
      - laravel_network
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  laravel_data:
    driver: local

networks:
  laravel_network:
    driver: bridge
